CREATE TABLE ELLA_ITEM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  PRODUCTID BIGINT NOT NULL,
  BRANDID BIGINT NOT NULL,  
  SIZEID BIGINT NOT NULL,  
  SKU VARCHAR(100) NOT NULL,
  MRP FLOAT NOT NULL DEFAULT 0,
  DISCOUNT FLOAT NOT NULL DEFAULT 0,
  MAXDISCOUNT FLOAT NULL,
  PRICE FLOAT NOT NULL DEFAULT 0,
  QUANTITY SMALLINT(6) NOT NULL DEFAULT 0,
  SOLD SMALLINT(6) NOT NULL DEFAULT 0,
  AVAILABLE SMALLINT(6) NOT NULL DEFAULT 0,
  DEFECTIVE SMALLINT(6) NOT NULL DEFAULT 0,
  CREATEDBY BIGINT NOT NULL,
  UPDATEBY BIGINT DEFAULT NULL,
  CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATEDDATE DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  INDEX `idx_item_product` (PRODUCTID ASC),
  CONSTRAINT `fk_item_product`
    FOREIGN KEY (PRODUCTID)
    REFERENCES ELLA_PRODUCT (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

ALTER TABLE ELLA_ITEM 
ADD INDEX `idx_item_brand` (BRANDID ASC);
ALTER TABLE ELLA_ITEM
ADD CONSTRAINT `fk_item_brand`
  FOREIGN KEY (BRANDID)
  REFERENCES ELLA_BRAND (ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE ELLA_ITEM
ADD INDEX `idx_item_size` (SIZEID ASC);
ALTER TABLE ELLA_ITEM 
ADD CONSTRAINT `fk_item_size`
  FOREIGN KEY (SIZEID)
  REFERENCES ELLA_SIZE (ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;